apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-persistent-claim
  namespace: davulv
spec:
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi